spring.application.name=siger-api

# Datasource configuration
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.tuofyzfghjqbkykkgrnz&password=aGogrSgX3suTEFmo
spring.datasource.username=postgres
spring.datasource.password=aGogrSgX3suTEFmo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=bd_siger

# JPA and Hibernate properties
# utilizar 'none' no campo abaixo quando usar o flyway.
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Flyway
# spring.flyway.enabled=true
# spring.flyway.locations=classpath:db/migration
# flyway.ignoreDatabaseVersion=true
